name: Data refresh

on:
  schedule:
    - cron:  '30 8 * * *'
  workflow_dispatch:

jobs:
  loadData:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: loaders

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: node ./cz-hospitalizace.js
      continue-on-error: true
    - run: node ./cz-news.js
      continue-on-error: true
    - run: node ./cz-ockovani.js
      continue-on-error: true
    - run: node ./cz-okresy2.js
      continue-on-error: true
    - run: node ./cz-r0.js
      continue-on-error: true
    - name: Commit
      run: |
        git config --global user.name 'Data loader action'
        git config --global user.email 'tom.kmec@gmail.com'
        git commit -am "Data update"
        git push
